import type {
	SVELTEKIT_DATA_ENPOINTS,
	SVELTEKIT_DATA_ENPOINTS_DEV,
	SVELTEKIT_DATA_ENPOINTS_PROD,
	SVELTEKIT_DATA_ENPOINTS_QA,
	SVELTEKIT_SEARCH_ENPOINTS,
	SVELTEKIT_SEARCH_ENPOINTS_DEV,
	SVELTEKIT_SEARCH_ENPOINTS_PROD,
	SVELTEKIT_SEARCH_ENPOINTS_QA,
} from '../enums';

export type SVELTEKIT_DATA_ENPOINT_TYPE = 'SERVICE';

export type SVELTEKIT_SEARCH_ENPOINT_TYPE = 'SEARCH';

export type SVELTEKIT_ENPOINT_TYPE = SVELTEKIT_DATA_ENPOINT_TYPE | SVELTEKIT_SEARCH_ENPOINT_TYPE;

export type SVELTEKIT_ENPOINTS = SVELTEKIT_DATA_ENPOINTS | SVELTEKIT_SEARCH_ENPOINTS;

export type SVELTEKIT_DATA_ENPOINT_CONFIG = {
	[key in SVELTEKIT_DATA_ENPOINT_TYPE]:
		| SVELTEKIT_DATA_ENPOINTS
		| SVELTEKIT_DATA_ENPOINTS_PROD
		| SVELTEKIT_DATA_ENPOINTS_DEV
		| SVELTEKIT_DATA_ENPOINTS_QA;
};

export type SVELTEKIT_SEARCH_ENPOINT_CONFIG = {
	[key in SVELTEKIT_SEARCH_ENPOINT_TYPE]:
		| SVELTEKIT_SEARCH_ENPOINTS
		| SVELTEKIT_SEARCH_ENPOINTS_PROD
		| SVELTEKIT_SEARCH_ENPOINTS_DEV
		| SVELTEKIT_SEARCH_ENPOINTS_QA;
};

export type SVELTEKIT_STARTER_ENPOINT_CONFIG = SVELTEKIT_DATA_ENPOINT_CONFIG & SVELTEKIT_SEARCH_ENPOINT_CONFIG;
